title = "Airspace for Hugo"
baseURL = "/"
languageCode = "en-us"
theme = "airspace-hugo"

[menu]

  [[menu.header]]
    weight = 2
    name = "Blog"
    url = "/blog"

# The site's parameters
[params]

  date_format = "2 January 2006"

  home = "Home"

  [params.slider]
    enable = true
    title = "A revolutionary cleaning process"
    subtitle = "We believe that clean environments help to have a healthier work life.<br/> <br/>We created a simplified cleaning process that adjust to our client's preferences to deliver the best possible solutions for their needs."

  [params.wrapper]
    enable = true
    title = "Services"
    service1 = "• Floor"
    paragraph1 = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna" 
    service2 = "• Carpet"
    paragraph2 = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna"
    service3 = "• Janitorial"
    paragraph3 = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna"

  [params.blog]
    enable = true
    title = "Get The Latest On What We're doing"
    subtitle = "Catch up with us, anytime and anywhere"

  [params.feature]
    enable = true
    title = "About Us"
    content = "We are a local building cleaning services company located in San Diego. After being in the cleaning industry for more than 40 years, we've noticed that one big mistake in the cleaning industry is cross contamination. We want to change people's mind about cleaning and not just only consider something clean because it looks like it. You have to consider microparticles such as germs that can be on a surface that looks clean. That's why we came up with a process that truly kills germs and creates a healthier environment."
    [params.feature.button]

  [params.call]
    enable = true
    title = "We design delightful digital experiences."
    paragraph = "Read more about what we do and our philosophy of design. Judge for yourself The work and results we’ve achieved for other clients, and meet our highly experienced Team who just love to design."

  [params.contact]
    enable = true
    title = "Say Hello! Drop us a line."
    subtitle = "Don’t just take our word for it. Check out some of our latest work."
    email = "hello@cleasp.com"
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Stop by for a visit"
      address = "North Main Street, Brooklyn Australia"
      email = "Email: blasftw@gmail.com"
      phone = "Phone: +88 01672 506 744"
    [params.contact.gmaps]
      title = "We Also Count in Google Maps"